language: node_js
node_js:
  - "5.1"

# cache:
#   bundler: true
#   directories:
#     - node_modules

install:
  - npm install

before_script:
  - npm install karma-phantomjs-launcher --save-dev
  - export CONTINUOUS_INTEGRATION=true

script:
  - npm test

# IMPORTANT: set DEPLOY in travis ci settings env variables
# to docker hub's `trigger url` value
after_success:
  - $DEPLOY
