language: node_js
node_js:
  - "5.1"

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm test

# IMPORTANT: set DEPLOY in travis ci settings env variables
# to docker hub's `trigger url` value
after_success:
  - $DEPLOY
